config/routes.rb
Blog::Application.routes.draw do
  resources :comments
  
  resources :images
  resources :comments
  resources :products do
    member do
      post 'product_comments'
      post 'product_likes_and_dislikes'
      post 'product_reply_comment'
    end
    collection do
      get 'product_categories'
      post 'update_featured'
      delete 'delete_product_images'
    end
  end
  get '/profile/:id' => 'home#profile', as: "profile"
  get '/search' => 'home#search'
  post '/home/follow' => 'home#user_following'
  get 'home/user' => 'home#user_list'
  post '/user/rating' => 'home#user_ratings'
  get '/home/user_sorted' => 'home#user_sorted_products'
  get '/home/like_sorted' => 'home#like_sorted_products'
  get '/home/product_likes_sorted' => 'home#like_sorted_search_products'
  get '/home/date_sorted' => 'home#date_sorted_products'

  devise_for :users

   root 'home#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

	belongs_to :user
  has_many :category_products
  has_many :categories , through: :category_products
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
  has_many :product_tags
  has_many :tags, through: :product_tags

  searchable do
      text :title, :boost => 5
      text :categories do
        categories.map { |category| category.name }
      end
      text :tags do
        tags.map { |tag| tag.name }
      end
  end


  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :comments

  validates :title, :description, :presence => true

  acts_as_likeable

  attr_accessor :abc,:def

  def abc
    self.categories.collect(&:name).join(',')
  end

  def def
    self.tags.collect(&:name).join(',')
  end

  def abc=(value)
    self.categories.delete_all
    names = value.split(',')
    names.each do |n|

      category = Category.find(n)
      self.categories << category
    end
  end

  def def=(value)
    self.tags.delete_all
    tags = value.split(',')
    tags.each do |n|
      tag = Tag.find_by_name(n)
      if tag.nil?
        t = Tag.create(:name=>n)
        self.tags << t
      else
        self.tags << tag
      end
    end 
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy,:product_comments,:product_likes_and_dislikes,:product_reply_comment]

  respond_to :html

  def index
    @products = current_user.products.all.page(params[:page]).per(5)
    respond_with(@products)
  end

  def show
    @products = Product.all
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit

  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        current_user.products << @product
        format.html { redirect_to @product, notice: 'Product created successfully' }
        format.json { render json:  @product, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product updated successfully' }
        format.json { render json:  @product, status: :created, location: @company }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  def product_comments
    comment = Comment.new(comment_params)
    respond_to do |format|
      if comment.save
        @product.comments << comment
        current_user.comments << comment
        format.html { redirect_to @product, notice: 'Comment added successfully' }
        format.json { render json:  @product, status: :created, location: @company }
      else
        format.html { redirect_to @product, alert: 'Empty Comment not added. Try Again' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def product_reply_comment
    description = params["comment"]
    parent_id = params["parent_id"]
    @product_comment = @product.comments.where(:id=>parent_id).first
    @display = true
    comment = Comment.new(:description=>description , :parent_id=>parent_id)
    if comment.save
      @product.comments << comment
      current_user.comments << comment
    end
  end

  def product_likes_and_dislikes
    type = params["type"]
    if type=="like"
      current_user.like!(@product)
      @product.update_attributes(:total_likes=>@product.likers(User).count)
    else
      current_user.unlike!(@product)
    end
    count  = @product.likers(User).count
    @product.update_attributes(:total_likes=>@product.likers(User).count)
    render :json => {:message => 'success',:count=>count}
  end

  def product_categories
    category = Category.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.html
      format.json { render :json => category.map(&:attributes) }
    end
  end

  def update_featured
    # false all featured products
    f_product = current_user.products.where(:feature=>true)
    if !f_product.empty?
      f_product.first.update_attributes(:feature=>false)
    end

    # update product to featured
    product = Product.find(params[:id])
    if product.update_attributes(:feature=>true)
      render :json => {:message => 'success'}
    else
      render :json => {:message => 'error'}
    end
  end

  def delete_product_images
    @product = Product.find(params[:id])
    images = params[:ids]
    flag = true
    images.each do |image|
      img = Image.find(image)
      if !img.destroy
        flag = false
      end
    end
  end

  private
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title,:description,:pros,:cons,:price,:link,:abc,:def,images_attributes: [:avatar])
    end

    def comment_params
      params.require(:product).require(:comments_attributes).require("0").permit(:description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<input type="hidden" value=<%= @product.id %> id="product_id">
<%= form_for(@product, html: { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
    <div class="col-md-12">
      <div class="alert alert-danger">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <% @product.errors.full_messages.each do |msg| %>
            <ul>
              <li style="">
                <%= msg %>
              </li>
            </ul>
      <% end %>
    </div>
  <% end %>
  
  <!-- /.product-page -->
  <div class="product-page">
    
    <section class="textfiled-section">
      <div class="container">
        <div class="textfield-block">
          <h2>Product</h2>
          <div class="text-field">
            <label>Upload Picture</label>
            <%= f.fields_for :images,@product.images.build do |photo| %>
              <%= photo.file_field :avatar,class: "form-control product-img abc",id:"imgInp" %>
              <div class="preview_img_div"><img class="target" src="#" alt="your image" id="imgInppreview"/></div>
            <% end %>
            
            <%= button_tag "Add More Images",:type => 'button',:id=>"add-img" , :style=>"display:none;"%>
          </div>
          <div class="text-field">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control", id:"exampleInputName2" %>
          </div>
          <div class="text-field">
            <%= f.label :description %><br>
            <%= f.text_area :description , class: "form-control", rows:'5',maxlength:'500' %>
          </div>
          
          <div >
              <label id="category_label">Category</label>
              <%= f.text_field :abc, class: "form-control", id:"category", placeholder:"#product" %>
          <div>
          
          </div>
          
          <div class="text-field">
            <label>Hashtags</label>
            <%= f.text_field :def, class: "form-control", id:"hashtags" , placeholder:"Tags separated by comma"%>
          </div>
          
          <div class="text-field">
            <%= f.submit "Create Product" , class: "form-control", id: "create-product" %>
          </div>
        </div>
      </div>
    </section>

  </div>

  <!-- /.product-page -->
<% end %>

<script type="text/javascript">

  
    $(function() {
      $("#category").tokenInput("/products/product_categories.json", {
        crossDomain: false,
        preventDuplicates: true,
        prePopulate: $("#category").data("pre"),
        theme: "facebook"
      });

      

    });
    
</script>  

app/views/products/_product_comment_reply.html.erb
<% first_reply = @product.comments.where(:parent_id=>@product_comment.id).first %>

<% if !first_reply.nil? %>
  <div class="product-comment-detail under-comment" >

    <div class="product-comment-body">
      <div class="text-field">
        <span>
        <% if @product_comment.user.images.count < 1 %>
          <%= link_to image_tag("user.png", class: "comment-pic default-pic"),profile_path(product_comment.user) %>
        <% else %>
          <%= link_to image_tag(@product_comment.user.images.last.avatar.url(:reply), class: "comment-pic"
          ),profile_path(@product_comment.user) %>
        <% end %>
      </span>
      <p class="show-reply-comment"><%= first_reply.description %></p>

      </div>
    </div>
  </div>
<% end %>

<% all_replies = @product.comments.where(:parent_id=>@product_comment.id) %>

<div id="all_replies_<%= @product_comment.id %>div" style="display:none;">
  <% if all_replies.count > 1 %>
    <% all_replies.each do |reply| %>
      <div class="product-comment-detail under-comment" >
        <% if reply.id != first_reply.id %>
          <div class="product-comment-body">
            <div class="text-field">
              <span>
                <% if @product_comment.user.images.count < 1 %>
                  <%= link_to image_tag("user.png", class: "comment-pic default-pic"),profile_path(@product_comment.user) %>
                <% else %>
                  <%= link_to image_tag(@product_comment.user.images.last.avatar.url(:reply), class: "comment-pic"
                  ),profile_path(@product_comment.user) %>
                <% end %>
              </span>
              <p class="show-reply-comment"><%= reply.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="product-comment-detail under-comment" id="under-comment<%= @product_comment.id %>div" style="display:none;">
  <div class="product-comment-body">
    <div class="text-field">
      <span>
      <% if @product_comment.user.images.count < 1 %>
        <%= link_to image_tag("user.png", class: "comment-pic default-pic"),profile_path(@product_comment.user) %>
      <% else %>
        <%= link_to image_tag(@product_comment.user.images.last.avatar.url(:reply), class: "comment-pic"
        ),profile_path(@product_comment.user) %>
      <% end %>
    </span>
    <input type="hidden" value=<%= @product_comment.id %> id="comment_id">
    <textarea class="form-control reply-comment" rows="2" placeholder="Reply.." id ="<%= @product_comment.id %>" autofocus></textarea>
    </div>
  </div>
</div>
<% if all_replies.count > 1 %>
  <div style="width:100%;text-align:right;"><button type="button" class="load_reply" id="all_replies_<%= @product_comment.id %>">View all</button></div>
<% end %>

app/views/products/_product_images.html.erb
<% if !@product.images.nil? || !@product.images.empty? %>
  <% @product.images.each do |img| %>
    <% if img.avatar_file_name && img.persisted? %>
      <label class="show_product_images">
        <%= image_tag img.avatar.url(:small) %>
        <%= check_box_tag(:image_id, img.id) %>
      </label>
    <% end %>                
  <% end %>
<% end %>

app/views/products/delete_product_images.js.erb
$(document).ready(function(){
  $(".product_images_class").html("<%= escape_javascript(render partial: 'product_images' ) %>");  
});

app/views/products/edit.html.erb
<input type="hidden" value=<%= @product.id %> id="product_id">
<%= form_for(@product, html: { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
    <div class="col-md-12">
      <div class="alert alert-danger">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <% @product.errors.full_messages.each do |msg| %>
            <ul>
              <li style="">
                <%= msg %>
              </li>
            </ul>
      <% end %>
    </div>
  <% end %>
  
  <!-- /.product-page -->
  <div class="product-page">
    
    <section class="textfiled-section">
      <div class="container">
        <div class="textfield-block">
          <h2>Product</h2>
          <div class="text-field">
            <%= f.fields_for :images, @product.images.build do |photo| %>
              <%= photo.file_field :avatar,class: "form-control product-img abc", id:"imgInp" %>
              <div class="preview_img_div"><img class="target" src="#" alt="your image" id="imgInppreview"/></div>
            <% end %>
            
              
            <div class="product_images_class">
              <%= render "product_images" %>
            </div>
            <div>
              <% if @product.images.count > 0 %>
                <%= button_tag "Delete Images",:type => 'button',:id=>"delete-img" %>
              <% end %>
              <!-- <button id="delete-img">Delete Images</button> -->
              <%= button_tag "Add More Images",:type => 'button',:id=>"add-img" , :style=>"display:none;"%>
              
            </div>
            
          </div>
          <div class="text-field">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control", id:"exampleInputName2" %>
          </div>
          <div class="text-field">
            <%= f.label :description %><br>
            <%= f.text_area :description , class: "form-control", rows:'5' %>
          </div>
          
          <div>
            <div>
                <label id="category_label">Category</label>
                <%= f.text_field :abc, class: "form-control", id:"category", "data-pre" => @product.categories.map(&:attributes).to_json %>
            <div>
          </div>
          

          <div class="text-field">
            <label id="category_label">Hashtag</label>
            <%= f.text_field :def, class: "form-control", id:"exampleInputName2" %>
          </div>

          
          <div class="text-field">
            <%= f.submit "Update Product" , class: "form-control", id: "create-product" %>
          </div>
        </div>
      </div>
    </section>

  </div>
  <!-- /.product-page -->
<% end %>

<script type="text/javascript">
  
  
  $(function() {
    $("#category").tokenInput("/products/product_categories.json", {
      crossDomain: false,
      prePopulate: $("#category").data("pre"),
      theme: "facebook"
    });
  });
  

</script>  

app/views/products/index.html.erb
<div class="profile-page search-result-page">
  <div class="container">
    
      <div class="row">
        <div class="col-md-3">
          <div class="search-heading">
            
          </div>
        </div>
        <div class="col-md-9">
          
          <div class="search_partial_products">
            <% @products.each do |product| %>
              <div class="search-result-widget-1">
                <div class="row">
                  <div class="col-md-4 col-sm-4 left-img-block">
                    <div class="person-block">
                      <% if product.images.count > 0 %>
                        
                        <%= link_to image_tag(product.images.first.avatar.url(:large), options={alt: "Logo"}),product.images.first.avatar.url, class: "colorbox" %>
                      <% else %>
                        <%= image_tag("product-img-1.png",:class=>"user_list_image") %>
                      <% end %>
                      <div class="profile-product-likes" style="margin-top:25px;">
                        <p>
                          <label for=featured_<%= product.id %>>Feature</label>
                          <%= radio_button_tag 'featured', product.id, product.feature == true ? true : false %>
                        </p>
                        <ul>
                          <li><a class="like"></a><span class="like_count"><%= product.total_likes  || 0 %></span></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-8 col-sm-8">
                    <div class="profile-product-detail" style="margin-bottom:10px;">
                      <h3><%= link_to product.title, product_path(product) %></h3>
                      <div class="profile-product-descrip">
                        <p><%= product.description %></p>
                      </div>
                    </div>
                    <% if product.user == current_user %>
                      <div class="profile-product-buttons" style="text-align:right;">
                        <%= link_to "Edit Button",edit_product_path(product),:class=>"list-product-edit" %>
                        <%= link_to "Destroy Button",product, method: :delete, data: { confirm: 'Are you sure?' },:class=>"list-product-delete" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div id="pagination"><%= paginate @products %></div>

            <% if @products.count < 1 %>
              <h2 style="padding:50px;">No records found</h2>
            <% end %>
          </div>
          
        </div>
      </div>
  </div>
</div>


<script type="text/javascript">
  $('input[type=radio][name=featured]').change(function() {
     var id = this.value;
     var url_link = '/products/update_featured';
      $.ajax({
          url: url_link,
          type: "POST",
          data: {id: id},
          success: function (data) {
              if(data.message = "success"){
                  
              }
              else{
                  alert('not featured')
              }
              
          }
      });
  });

  <script type="text/javascript">
    $('a.colorbox').colorbox();
  </script>
  
</script>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/product_reply_comment.js.erb
$(document).ready(function(){
	var q = "#comment_replies<%= @product_comment.id %>";
  	$(q).html("<%= escape_javascript(render partial: 'product_comment_reply' ) %>");

  	var all_replies = "#all_replies_<%= @product_comment.id %>div";
  	$(all_replies).show();

  	var view_button = "#all_replies_<%= @product_comment.id %>";
  	$(view_button).hide();
});

app/views/products/show.html.erb
<input type="hidden" value=<%= @product.id %> id="product_id">
<!-- /.product-page-detail -->
  <div class="product-page-detail">
    <div class="container">

      
      <section class="product-carousel">
        <div class="product-des">
          <div class="product-heading">
            <%= @product.title %>
          </div>
          <div class="product-author">
            <%= link_to @product.user.name, profile_path(@product.user) %>
          </div>
        </div>
        
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          
          <ol class="carousel-indicators">
            <% count=0 %>
            <% if @product.images.count > 1 %> 
              <% @product.images.each do |image| %>
                <% if count == 0 %>
                  <li data-target="#carousel-example-generic" data-slide-to=<%= count %> class="active">
                <% else %>
                  <li data-target="#carousel-example-generic" data-slide-to=<%= count %> >
                <% end %>
                </li>
                <% count=count+1 %>
              <% end %>

            <% end %>
            
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
              <% active=0 %>
              <% @product.images.each do |image| %>
                <% if active == 0 %>
                  <div class="item active">
                <% else %>
                  <div class="item">
                <% end %>
                <%= image_tag(image.avatar.url(:slider_image)) %>
                </div>
                <% active=active+1 %>
              <% end %>
              <% if @product.images.count < 1 %>
                <div class="item active">
                  <%= image_tag("product-img-1.png", class: "style_image") %>
                </div>
              <% end %>
          </div>
        </div>
      </section>
      <section class="product-details">
        <div class="container-product-details">
          <div class="row">
            <div class="col-md-6">
              <!-- <div class="product-details-rating">
                <p>Rating:</p>
                <ul>
                  <li><a href="#"><span></span></a></li>
                  <li><a href="#"><span></span></a></li>
                  <li><a href="#"><span></span></a></li>
                  <li><a href="#"><span></span></a></li>
                  <li><a href="#"><span></span></a></li>
                </ul>
              </div> -->
              <div class="product-details-like">
                <ul>
                  <% if current_user.likes?(@product) %>
                    <li><a class="dislike" id=<%= "#{@product.id}" %> ></a><span class="like_count"><%= @product.total_likes  || 0%></span></li>
                  <% else %> 
                    <li><a class="like" id=<%= "#{@product.id}" %> ></a><span class="like_count"><%= @product.total_likes || 0 %></span></li>
                  <% end -%>
                </ul>
              </div>
            </div>
            <div class="col-md-6">
              <div class="product-details-date">
                
                <span><%= @product.created_at.strftime("%d/%m/%Y") %></span>
                
                <%= image_tag("img-8.png", options={alt: "Logo"}) %>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="product-descrip">
        <div class="container-product-descrip">
          <div class="row">
            <div class="col-md-12">
              <div class="product-descrip-detail">
                
                <div class="product-detail">
                  <div class="product-detail-bg">
                    <p><%= simple_format h @product.description %></p>
                  </div>
                </div>
                
                <div class="product-detail">
                  <% if !@product.categories.empty? %>
                    <div class="product-detail-bg">
                        <% @product.categories.each do |category| %>
                          <span class="label label-primary"><%= category.name %></span>
                        <% end %>
                    </div>
                  <% end %>
                </div>
                <div class="product-detail">
                  <% if @product.tags.count>0 %>
                    <div class="product-detail-bg">
                        <% @product.tags.each do |tag| %>
                          <%= link_to "#"+tag.name ,search_path(:type=>"hashtag",:search=>tag.name ),:class=>"label label-primary", :id=>"tag_style" %>
                        <% end %>
                    </div>
                  <% end %>
                </div>
                
          </div>
        </div>
      </section>
      <section class="product-comment">
        <div class="container-product-comment">
          <div class="row">
            <div class="col-md-12">
                <% if !@product.comments.empty? %>
                  <div class="product-comment-detail">
                    <h3>Comments</h3>
                    <% product_comments = @product.comments.all.where(:parent_id=>nil).page(params[:page]).per(10) %>
                    <% product_comments.each do |product_comment| %>
                        <div class="product-comment-info">
                          <div class="product-comment-user">
                            <span>
                              <% if product_comment.user.images.count < 1 %>
                                <%= link_to image_tag("user.png", class: "comment-pic default-pic"),profile_path(product_comment.user) %>
                              <% else %>
                                <%= link_to image_tag(product_comment.user.images.last.avatar.url(:small), class: "comment-pic"
                                ),profile_path(product_comment.user) %>
                              <% end %>
                            </span>
                            <h3><%= link_to product_comment.user.name, profile_path(product_comment.user) %></h3>
                          </div>
                          <div class="product-comment-date">
                            <span style="width:auto;display:inline;"><%= product_comment.created_at.strftime("%d/%m/%Y") + " at " + product_comment.created_at.strftime("%H:%M") %></span>
                            <span class="reply"><i class="fa fa-reply" id="under-comment<%= product_comment.id %>"></i></span>
                            <% if product_comment.user == current_user %>
                              <span class="edit" data-toggle="tooltip" data-placement="left" title="Click on Comment to Edit">
                                  <i class="fa fa-pencil" id ="best_in_place_comment_<%= product_comment.id %>_description"></i>
                              </span>
                            <% end %>
                          </div>
                          <div class="text-field">
                            
                            <% if product_comment.user == current_user %>
                              <p><%= best_in_place product_comment, :description, :nil => "Click me to add content!"  %></p>
                              
                            <% else %>
                              <p><%= product_comment.description %></p>
                            <% end %>  
                          </div>
                        </div>
                        <div id="comment_replies<%= product_comment.id %>">
                          <%= render :partial => "product_comment_reply", :locals => {:@product_comment => product_comment} %>
                        </div>
                                
                    <% end %>
                    <div style="text-align:center;">
                      <%= paginate product_comments %>
                    </div>
                  </div>
                  <div class="product-comment-detail under-comment" >
                    <div class="product-comment-body">
                      <div class="new_comment_field">
                        <%= form_for @product , url: product_comments_product_path(@product), :method => :post do |f| %>
                          <%= f.fields_for :comments, @product.comments.build do |comment| %>
                            <%= comment.text_area :description, :required => true, :class=>"form-control", placeholder: "Add comment here.." %>
                          <% end %>
                          <%= f.submit "Add Comment", :id=>"create-comment" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% else %>
                  <h3>No Comment</h3>
                    
                  <div class="product-comment-detail under-comment" style="padding-top:20px;">
                    <div class="product-comment-body">
                      <div class="new_comment_field">
                        <%= form_for @product , url: product_comments_product_path(@product), :method => :post do |f| %>
                          <%= f.fields_for :comments, @product.comments.build do |comment| %>
                            <%= comment.text_area :description, :required => true,:class=>"form-control", placeholder: "Add comment here.." %>
                          <% end %>
                          <%= f.submit "Add comment", :id=>"create-comment" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
            </div>
          </div>
        </div>
      </section>

    </div>
  </div>
  <!-- /.product-page-detail -->
  <script type="text/javascript">
    $(".product-details-like ul li a").click(function() {
        var id = $(this).attr('id');
        var url_link = '/products/'+id+'/product_likes_and_dislikes';
        var current_id = $(this).attr('class');
        $.ajax({
            url: url_link,
            type: "POST",
            data: {type: current_id},
            success: function (data) {
                if(current_id == "dislike"){
                    $("#"+id).removeClass(current_id).addClass('like');
                    $("#"+id).siblings('.like_count').html(data.count);
                }
                else{
                    $("#"+id).removeClass(current_id).addClass('dislike');
                    $("#"+id).siblings('.like_count').html(data.count);
                }
                
            }
        });
    });

  </script>