config/routes.rb
Blog::Application.routes.draw do
  resources :comments
  
  resources :images
  resources :comments
  resources :products do
    member do
      post 'product_comments'
      post 'product_likes_and_dislikes'
      post 'product_reply_comment'
    end
    collection do
      get 'product_categories'
      post 'update_featured'
      delete 'delete_product_images'
    end
  end
  get '/profile/:id' => 'home#profile', as: "profile"
  get '/search' => 'home#search'
  post '/home/follow' => 'home#user_following'
  get 'home/user' => 'home#user_list'
  post '/user/rating' => 'home#user_ratings'
  get '/home/user_sorted' => 'home#user_sorted_products'
  get '/home/like_sorted' => 'home#like_sorted_products'
  get '/home/product_likes_sorted' => 'home#like_sorted_search_products'
  get '/home/date_sorted' => 'home#date_sorted_products'

  devise_for :users

   root 'home#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :tokens, :through => :taggings
	has_many :taggings, :as => :taggable
 
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_products
  has_many :products , through: :category_products

  searchable do
    text :name
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :description, :presence => true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
  has_attached_file :avatar, styles: { reply: "50x50>" ,profile: "263X263>", thumb: "30x30>", small: "66x66>", med: "150x84>", large: "200x146>", e_large: "800x449>", slider_image: "1140x600>"}
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like

  def self.like_ids
    all.map(&:likeable_id)
  end

  def self.products
    Product.where(id: like_ids)
  end

end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/product.rb
class Product < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

	belongs_to :user
  has_many :category_products
  has_many :categories , through: :category_products
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
  has_many :product_tags
  has_many :tags, through: :product_tags

  searchable do
      text :title, :boost => 5
      text :categories do
        categories.map { |category| category.name }
      end
      text :tags do
        tags.map { |tag| tag.name }
      end
  end


  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :comments

  validates :title, :description, :presence => true

  acts_as_likeable

  attr_accessor :abc,:def

  def abc
    self.categories.collect(&:name).join(',')
  end

  def def
    self.tags.collect(&:name).join(',')
  end

  def abc=(value)
    self.categories.delete_all
    names = value.split(',')
    names.each do |n|

      category = Category.find(n)
      self.categories << category
    end
  end

  def def=(value)
    self.tags.delete_all
    tags = value.split(',')
    tags.each do |n|
      tag = Tag.find_by_name(n)
      if tag.nil?
        t = Tag.create(:name=>n)
        self.tags << t
      else
        self.tags << tag
      end
    end 
  end
  
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :product
  belongs_to :tag
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :rate_able, polymorphic: true
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags

  searchable do
    text :name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	belongs_to :token
	belongs_to :taggable, :polymorphic => true
end

app/models/token.rb
class Token < ActiveRecord::Base
	has_many :books, :through => :taggings, :source => :taggable, :source_type => "Book"
	has_many :taggings
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable
  validates :name, :presence => true

  acts_as_liker
  acts_as_follower
  acts_as_followable
  
	has_many :products
  has_many :comments
  has_many :ratings, as: :rate_able
  has_many :images, as: :imageable
  
  searchable do
    text :name
    text :first_name
    text :last_name
  end

  accepts_nested_attributes_for :images

  def self.user_ids
    all.map(&:id)
  end

  def self.products
    Product.where(user_id: user_ids)
  end

end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!

    flash_alerts = []

    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
    end

    return '' if resource.errors.empty?  && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages
    
    #messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    messages = errors.map { |msg| content_tag(:li, " #{msg}") }.join
    if !flash[:notice].nil?
      html = <<-HTML
      <div class="alert alert-info" style="list-style-type:none;"> <button type="button"
      class="close" data-dismiss="alert">x</button>
        #{messages}
      </div>
      HTML
    else
      html = <<-HTML
    <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML
    end
    

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<% if !devise_controller? %>
  <body>
    <!-- header -->
    <header>
      <div class="container">
        <div class="upper-header">
          <div class="header-container">
            <div class="row">
              <div class="col-md-12">
                <div class="upper-header-content dropdown">
                  <ul>
                    <li><%= link_to('Create Product', new_product_path ) %></li>
                    <li><a href="#" class="user-link">
                      <% if current_user.images.nil? || current_user.images.empty? %>
                        <%= link_to image_tag("user.png", class: "profile-img"), asset_path("user.png"), class: "colorbox" %>
                      <% else %>
                        <%= link_to image_tag(current_user.images.last.avatar.url(:thumb), class: "profile-img"),current_user.images.last.avatar.url, class: "colorbox" %>
                        
                      <% end %>

                      <%= link_to current_user.name, profile_path(current_user) %></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle setting-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
                      <ul class="dropdown-menu setting-menu">
                        
                        <li><%= link_to('Create Product', new_product_path , class: 'logout-link') %></li>
                        <li><%= link_to('All Products', products_path , class: 'logout-link') %></li>
                        <li><%= link_to('Edit Profile', edit_user_registration_path , class: 'logout-link') %></li>
                        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete , class: 'logout-link') %></li>

                      </ul>
                    </li>
                    <li><a href="#" class="question-link"><span></span></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="main-header">
          <nav class="navbar navbar-default">
            <div class="header-container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("logo.png", options={alt: "Logo"}), root_url, :class => "navbar-brand" %>
              </div>
              <%= form_tag('/search', method: :get) do %>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <div class="form-group" style="margin-bottom:0;padding-bottom:0;">
                    
                      <p>
                        <%= text_field_tag :search, params[:search],:class=>"form-control",:placeholder=>"Search by hashtag, user, product, category..." %>
                          <span id="search_span"><i class="fa fa-search"></i></span>
                        <%= submit_tag "Search", :name => nil, :id=>"search_submit" %>
                      </p>
                    
                    
                  </div>
                  <ul class="form-chk">
                    <% @type ||= "product" %>
                    <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'All', @type == "All" ? true : false %> All
                      </label>
                    </li>
                    <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'user', @type == "user" ? true : false %> User
                      </label>
                    </li>
                    <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'hashtag', @type == "hashtag" ? true : false %>  Hashtag
                      </label>
                    </li>
                    <!-- <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'user', @type == "user" ? true : false %> User
                      </label>
                    </li> -->
                    <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'product', @type == "product" ? true : false %> Product
                      </label>
                    </li>
                    <li>
                      <label class="checkbox-inline">
                        <%= radio_button_tag 'type', 'category', @type == "category" ? true : false %> Category
                      </label>
                    </li>
                  </ul>

              </div>
              <% end %>
            </div>
          </nav>
        </div>
      </div>
      <% flash.each do |key, value| %>
        <% if key == "alert" %>
          <div class="alert alert-danger">
            <a href="#" data-dismiss="alert" class="close">×</a>
              <ul>
                <li style="list-style-type:none;">
                  <%= value %>
                </li>
              </ul>
          </div>
        <% else %>
          <div class="alert alert-info">
            <a href="#" data-dismiss="alert" class="close">×</a>
              <ul>
                <li style="list-style-type:none;">
                  <%= value %>
                </li>
              </ul>
          </div>

        <% end %>
        
      <% end %>
    </header>
    <!-- header -->
    <% end %>
  	<%= yield %>

    <% if !devise_controller? %>
    <!-- footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="footer-content">
              <p>All Rights Reseved</p>
            </div>
          </div>
        </div>
      </div>
      
    </footer>
    <!-- footer -->

  </body>
<% else %>
  <body class="login-page">

    

  </body>
<% end %>
</html>
<script type="text/javascript">
  $("#search_span").click(function(){
      $('form').submit();
      return false;
  });
</script>